force-app/main/default/objects/objfordynamicvfpage__c/objfordynamicvfpage__c.object-meta.xml
<CustomObject>
    <label>objfordynamicvfpage</label>
    <nameField>
        <label>objfordynamicvfpage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>objfordynamicvfpages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/objfordynamicvfpage__c/fields/F1_Text__c.field-meta.xml
<CustomField>
    <fullName>F1_Text__c</fullName>
    <label>F1_Text</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/objfordynamicvfpage__c/fields/F2_Number__c.field-meta.xml
<CustomField>
    <fullName>F2_Number__c</fullName>
    <label>F2_Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/objfordynamicvfpage__c/fields/F3_Ceckbox__c.field-meta.xml
<CustomField>
    <fullName>F3_Ceckbox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>F3_Ceckbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/oFieldLabel__c/oFieldLabel__c.object-meta.xml
<CustomObject>
    <label>oFieldLabel</label>
    <nameField>
        <label>oFieldLabel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>oFieldLabels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/oFieldLabel__c/fields/FieldLabel__c.field-meta.xml
<CustomField>
    <fullName>FieldLabel__c</fullName>
    <label>FieldLabel</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/oFieldLabel__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>FieldName</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/dynamicvfp_controller.cls
Public Class dynamicvfp_controller{

    // Initatingthe Variables
    String Label = 'Ann Revenue Controller'; 
    String Label1;
    String Label2;
    String Label3;   
    String CalledMethod;
    
    List<User> UsersCountry{get; set;}
    
    Public dynamicvfp_controller(Apexpages.StandardController cont){}

   // UsersCountry Methods
   Public List<User> UsersCountry() {
    return [SELECT Country FROM User where ID = :UserInfo.getUserID() ];
   } 

   // Method to fetch dynamic label of fields
   Public Void ProcessLabels(){  
    // Getting User Country Code from User object() ;
    UsersCountry = this.UsersCountry();
    // Preparing List of record from oFieldLabel    
    List<oFieldLabel__c> FD1L = [Select FieldLabel__c, FieldName__c from oFieldLabel__c where FieldName__c in('FD1','FD2','FD3') and Country_Code__c=:UsersCountry[0].Country];
           
    for(oFieldLabel__c F:FD1L){
    
        if (CalledMethod == 'Label1'){
              if(F.FieldName__c=='FD1'){
                    Label1 = F.FieldLabel__c;
               }
        }
        
        if (CalledMethod == 'Label2'){       
              if(F.FieldName__c=='FD2'){
                Label2 = F.FieldLabel__c;           
              }
        }
        
        if (CalledMethod == 'Label3'){      
            if(F.FieldName__c=='FD3'){
               Label3 = F.FieldLabel__c;               
               //Label3 = 'User Country : ' + UsersCountry[0].Country + ' User Name : ' + UserInfo.getUserName() ;
            }
       }
             
     }   
   }
   
   // Returns the List of all Employees            
    Public List<objfordynamicvfpage__c> getAll_Employee(){
        List<objfordynamicvfpage__c> All_Employee = [Select Name, F1_Text__c, F2_Number__c, F3_Ceckbox__c from objfordynamicvfpage__c];
        return All_Employee ;
    }

   // Returns Label1
   Public String getLabel1(){
   CalledMethod = 'Label1';
   this.ProcessLabels();   
   return Label1;
   }

   // Returns Label2   
   Public String getLabel2(){
   CalledMethod = 'Label2';
   this.ProcessLabels();
   return Label2;
   } 

   // Returns Label3    
   Public String getLabel3(){
   CalledMethod = 'Label3';
   this.ProcessLabels();
   return Label3;
   } 

}